import type { Belt } from "./types";

export const kyuBelts: Belt[] = [
  {
    id: "kyu-10",
    color: "Trắng",
    colorHex: "#ffffff",
    kyu: 10,
    name: "Đai Trắng",
    requirements: ["Nhập môn", "Học Heian Shodan", "Kihon cơ bản"],
  },
  {
    id: "kyu-9",
    color: "Trắng-Vàng",
    colorHex: "#f5e642",
    kyu: 9,
    name: "Đai Trắng-Vàng",
    requirements: ["Heian Shodan", "Kihon đấm thẳng", "Cơ bản uke-waza"],
  },
  {
    id: "kyu-8",
    color: "Vàng",
    colorHex: "#f5c842",
    kyu: 8,
    name: "Đai Vàng",
    requirements: ["Heian Nidan", "Gyaku-zuki", "Mae-geri"],
  },
  {
    id: "kyu-7",
    color: "Cam",
    colorHex: "#f58c42",
    kyu: 7,
    name: "Đai Cam",
    requirements: ["Heian Sandan", "Kihon combo 3 bước", "Kumite kihon"],
  },
  {
    id: "kyu-6",
    color: "Xanh lá",
    colorHex: "#4caf50",
    kyu: 6,
    name: "Đai Xanh lá",
    requirements: ["Heian Yondan", "Mawashi-geri", "Ippon kumite"],
  },
  {
    id: "kyu-5",
    color: "Xanh lá đậm",
    colorHex: "#2e7d32",
    kyu: 5,
    name: "Đai Xanh lá đậm",
    requirements: ["Heian Godan", "Kihon nâng cao", "Sanbon kumite"],
  },
  {
    id: "kyu-4",
    color: "Xanh dương",
    colorHex: "#1565c0",
    kyu: 4,
    name: "Đai Xanh dương",
    requirements: ["Tekki Shodan", "Ushiro-geri", "Jiyu ippon kumite"],
  },
  {
    id: "kyu-3",
    color: "Xanh dương đậm",
    colorHex: "#0d47a1",
    kyu: 3,
    name: "Đai Xanh dương đậm",
    requirements: ["Bassai Dai", "Kihon nâng cao cấp 3", "Jiyu kumite cơ bản"],
  },
  {
    id: "kyu-2",
    color: "Nâu",
    colorHex: "#6d4c41",
    kyu: 2,
    name: "Đai Nâu",
    requirements: ["Kanku Dai", "Kata tự chọn", "Jiyu kumite"],
  },
  {
    id: "kyu-1",
    color: "Nâu đậm",
    colorHex: "#4e342e",
    kyu: 1,
    name: "Đai Nâu đậm",
    requirements: ["Bassai Sho hoặc Kanku Sho", "Kata tự chọn nâng cao", "Jiyu kumite tốc độ cao"],
  },
];

export const danBelts: Belt[] = [
  {
    id: "dan-1",
    color: "Đen",
    colorHex: "#1a1815",
    dan: 1,
    name: "Shodan",
    requirements: ["Kata Bassai Dai + 1 kata tự chọn", "Jiyu kumite trình diễn"],
  },
  {
    id: "dan-2",
    color: "Đen",
    colorHex: "#1a1815",
    dan: 2,
    name: "Nidan",
    requirements: ["Kata Kanku Dai + 2 kata tự chọn", "Kumite nâng cao"],
  },
  {
    id: "dan-3",
    color: "Đen",
    colorHex: "#1a1815",
    dan: 3,
    name: "Sandan",
    requirements: ["5 kata + 3 kata bunkai", "Giảng dạy thực hành"],
  },
  {
    id: "dan-4",
    color: "Đen",
    colorHex: "#1a1815",
    dan: 4,
    name: "Yondan",
    requirements: ["Yêu cầu tổ chức xét duyệt"],
  },
  {
    id: "dan-5",
    color: "Đen-Đỏ",
    colorHex: "#8b1a14",
    dan: 5,
    name: "Godan",
    requirements: ["Yêu cầu tổ chức xét duyệt"],
  },
  {
    id: "dan-6",
    color: "Đen-Đỏ",
    colorHex: "#8b1a14",
    dan: 6,
    name: "Rokudan",
    requirements: ["Yêu cầu tổ chức xét duyệt"],
  },
  {
    id: "dan-7",
    color: "Đen-Đỏ",
    colorHex: "#8b1a14",
    dan: 7,
    name: "Shichidan",
    requirements: ["Yêu cầu tổ chức xét duyệt"],
  },
  {
    id: "dan-8",
    color: "Đỏ-Trắng",
    colorHex: "#c43d36",
    dan: 8,
    name: "Hachidan",
    requirements: ["Yêu cầu tổ chức xét duyệt"],
  },
  {
    id: "dan-9",
    color: "Đỏ",
    colorHex: "#8b1a14",
    dan: 9,
    name: "Kudan",
    requirements: ["Yêu cầu tổ chức xét duyệt"],
  },
  {
    id: "dan-10",
    color: "Đỏ",
    colorHex: "#8b1a14",
    dan: 10,
    name: "Judan",
    requirements: ["Danh dự — không thể thỉnh cầu"],
  },
];

export const allBelts: Belt[] = [...kyuBelts, ...danBelts];
