import type { ClassSchedule } from "./types";

export const classSchedules: ClassSchedule[] = [
  // Thuận Giao 1 — Thầy Việt
  {
    id: "tg1-mon-wed-fri-kids",
    locationId: "thuan-giao-1",
    dayOfWeek: "monday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "kids",
    level: "all",
    instructorId: "nguyen-van-viet",
    capacity: 30,
  },
  {
    id: "tg1-wed-kids",
    locationId: "thuan-giao-1",
    dayOfWeek: "wednesday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "kids",
    level: "all",
    instructorId: "nguyen-van-viet",
    capacity: 30,
  },
  {
    id: "tg1-fri-kids",
    locationId: "thuan-giao-1",
    dayOfWeek: "friday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "all",
    level: "all",
    instructorId: "nguyen-van-viet",
    capacity: 40,
  },
  // Thuận Giao 2 — Thầy Việt
  {
    id: "tg2-tue-adults",
    locationId: "thuan-giao-2",
    dayOfWeek: "tuesday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "adults",
    level: "beginner",
    instructorId: "nguyen-van-viet",
    capacity: 25,
  },
  {
    id: "tg2-thu-all",
    locationId: "thuan-giao-2",
    dayOfWeek: "thursday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "all",
    level: "intermediate",
    instructorId: "nguyen-van-viet",
    capacity: 25,
  },
  // Thuận Giao 3 — Cô Nhi
  {
    id: "tg3-tue-nhi",
    locationId: "thuan-giao-3",
    dayOfWeek: "tuesday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "kids",
    level: "beginner",
    instructorId: "vo-thi-yen-nhi",
    capacity: 35,
  },
  {
    id: "tg3-thu-nhi",
    locationId: "thuan-giao-3",
    dayOfWeek: "thursday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "teens",
    level: "intermediate",
    instructorId: "vo-thi-yen-nhi",
    capacity: 30,
  },
  {
    id: "tg3-sat-nhi",
    locationId: "thuan-giao-3",
    dayOfWeek: "saturday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "all",
    level: "all",
    instructorId: "vo-thi-yen-nhi",
    capacity: 50,
  },
  // THCS Thuận Giao — Thầy Quân
  {
    id: "thcs-tue-quan",
    locationId: "thcs-thuan-giao",
    dayOfWeek: "tuesday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "teens",
    level: "beginner",
    instructorId: "van-anh-quan",
    capacity: 40,
  },
  {
    id: "thcs-thu-quan",
    locationId: "thcs-thuan-giao",
    dayOfWeek: "thursday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "adults",
    level: "advanced",
    instructorId: "van-anh-quan",
    capacity: 20,
  },
  {
    id: "thcs-sat-quan",
    locationId: "thcs-thuan-giao",
    dayOfWeek: "saturday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "all",
    level: "intermediate",
    instructorId: "van-anh-quan",
    capacity: 40,
  },
  // An Thạnh — Cô Nhi
  {
    id: "at-mon-nhi",
    locationId: "an-thanh",
    dayOfWeek: "monday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "kids",
    level: "all",
    instructorId: "vo-thi-yen-nhi",
    capacity: 30,
  },
  {
    id: "at-wed-nhi",
    locationId: "an-thanh",
    dayOfWeek: "wednesday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "teens",
    level: "beginner",
    instructorId: "vo-thi-yen-nhi",
    capacity: 30,
  },
  {
    id: "at-fri-nhi",
    locationId: "an-thanh",
    dayOfWeek: "friday",
    startTime: "17:30",
    endTime: "19:00",
    ageGroup: "adults",
    level: "all",
    instructorId: "vo-thi-yen-nhi",
    capacity: 25,
  },
  // Thanh Nhã — Evening
  {
    id: "tn-sat-evening",
    locationId: "thanh-nha",
    dayOfWeek: "saturday",
    startTime: "19:15",
    endTime: "20:45",
    ageGroup: "adults",
    level: "advanced",
    instructorId: "nguyen-van-viet",
    capacity: 20,
  },
];
