import type { Locale } from "@/shared/i18n";

import type { Instructor } from "./types";

export const instructors: Record<Locale, Instructor[]> = {
  vi: [
    {
      id: "nguyen-van-viet",
      slug: "nguyen-van-viet",
      name: "Thầy Nguyễn Văn Việt",
      title: "Chủ nhiệm Võ đường",
      bio: "Thầy Việt là người sáng lập Võ đường Tâm Việt, có hơn 20 năm kinh nghiệm giảng dạy karate và đã đào tạo hàng nghìn võ sinh.",
      photo: "/images/instructors/mr-viet",
      achievements: [
        "Huy chương Vàng Giải Karate Quốc gia 2008",
        "Chứng nhận WKF International Instructor",
        "Sáng lập Võ đường Tâm Việt năm 2010",
        "Huấn luyện hơn 1.000 võ sinh đạt đai đen",
      ],
      yearsTeaching: 20,
      beltRank: "Đai đen 3 đẳng",
      contact: { phone: "098 131 63 779" },
    },
    {
      id: "vo-thi-yen-nhi",
      slug: "vo-thi-yen-nhi",
      name: "Cô Võ Thị Yến Nhi",
      title: "Huấn luyện viên",
      bio: "Cô Yến Nhi có phương pháp giảng dạy tận tình và hiệu quả, chuyên phụ trách lớp thiếu nhi và nữ sinh.",
      photo: "/images/instructors/ms-nhi",
      achievements: [
        "Huy chương Bạc Giải Karate Toàn quốc 2018",
        "Chứng nhận WKF Coach Level 1",
        "Chuyên gia đào tạo karate thiếu nhi",
      ],
      yearsTeaching: 5,
      beltRank: "Đai đen 2 đẳng",
    },
    {
      id: "van-anh-quan",
      slug: "van-anh-quan",
      name: "Thầy Văn Anh Quân",
      title: "Huấn luyện viên",
      bio: "Thầy Anh Quân đã dẫn dắt nhiều võ sinh đạt thành tích cao trong các giải đấu trong nước và quốc tế.",
      photo: "/images/instructors/mr-quan",
      achievements: [
        "Top 3 Giải Karate Trẻ Toàn quốc 2019",
        "Chứng nhận WKF Coach Level 1",
        "Huấn luyện viên kumite chuyên nghiệp",
      ],
      yearsTeaching: 5,
      beltRank: "Đai đen 1 đẳng",
    },
  ],
  en: [
    {
      id: "nguyen-van-viet",
      slug: "nguyen-van-viet",
      name: "[EN] Master Nguyen Van Viet",
      title: "[EN] Head Instructor",
      bio: "[EN] Master Viet founded Tam Viet Dojo with over 20 years of karate teaching experience, having trained thousands of students.",
      photo: "/images/instructors/mr-viet",
      achievements: [
        "[EN] Gold Medal — National Karate Championship 2008",
        "[EN] WKF International Instructor Certified",
        "[EN] Founded Tam Viet Dojo in 2010",
        "[EN] Trained over 1,000 black belt students",
      ],
      yearsTeaching: 20,
      beltRank: "[EN] 3rd Dan Black Belt",
      contact: { phone: "098 131 63 779" },
    },
    {
      id: "vo-thi-yen-nhi",
      slug: "vo-thi-yen-nhi",
      name: "[EN] Instructor Vo Thi Yen Nhi",
      title: "[EN] Instructor",
      bio: "[EN] Instructor Yen Nhi specialises in children and female student training with dedicated, effective methods.",
      photo: "/images/instructors/ms-nhi",
      achievements: [
        "[EN] Silver Medal — National Karate Championship 2018",
        "[EN] WKF Coach Level 1 Certified",
      ],
      yearsTeaching: 5,
      beltRank: "[EN] 2nd Dan Black Belt",
    },
    {
      id: "van-anh-quan",
      slug: "van-anh-quan",
      name: "[EN] Instructor Van Anh Quan",
      title: "[EN] Instructor",
      bio: "[EN] Instructor Anh Quan has guided many students to competitive success at national and international levels.",
      photo: "/images/instructors/mr-quan",
      achievements: [
        "[EN] Top 3 — National Youth Karate Championship 2019",
        "[EN] WKF Coach Level 1 Certified",
      ],
      yearsTeaching: 5,
      beltRank: "[EN] 1st Dan Black Belt",
    },
  ],
  ja: [
    {
      id: "nguyen-van-viet",
      slug: "nguyen-van-viet",
      name: "[JA] グエン・ヴァン・ヴィエット師範",
      title: "[JA] 道場長",
      bio: "[JA] ヴィエット師範はタムヴィエット道場の創設者であり、20年以上の指導歴を持つ。",
      photo: "/images/instructors/mr-viet",
      achievements: [
        "[JA] 全国大会金メダル 2008年",
        "[JA] WKF国際指導員認定",
        "[JA] 2010年タムヴィエット道場設立",
      ],
      yearsTeaching: 20,
      beltRank: "[JA] 三段",
      contact: { phone: "098 131 63 779" },
    },
    {
      id: "vo-thi-yen-nhi",
      slug: "vo-thi-yen-nhi",
      name: "[JA] ヴォー・ティ・イェン・ニー指導員",
      title: "[JA] 指導員",
      bio: "[JA] 熱心な指導で知られ、子供・女性クラスを専門とする。",
      photo: "/images/instructors/ms-nhi",
      achievements: ["[JA] 全国大会銀メダル 2018年", "[JA] WKFコーチ認定"],
      yearsTeaching: 5,
      beltRank: "[JA] 二段",
    },
    {
      id: "van-anh-quan",
      slug: "van-anh-quan",
      name: "[JA] ヴァン・アン・クアン指導員",
      title: "[JA] 指導員",
      bio: "[JA] 多くの生徒を国内外の試合で入賞へ導いてきた。",
      photo: "/images/instructors/mr-quan",
      achievements: ["[JA] 全国ジュニア大会第3位 2019年"],
      yearsTeaching: 5,
      beltRank: "[JA] 初段",
    },
  ],
};
